<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-8LOUFHRQ" failures="1" tests="2" name="cucumber.TestNGTestRunner" time="14.510" errors="0" timestamp="2025-01-24T16:55:18 ICT" skipped="0">
  <testcase classname="cucumber.TestNGTestRunner" name="runScenario" time="7.658">
    <failure message="expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found [Warning: No match for E-Mail Address and/or Password.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found [Warning: No match for E-Mail Address and/or Password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at ojosanco.stepDefinitions.StepDefinitionImpl.something_message_is_displayed(StepDefinitionImpl.java:276)
at âœ½."Warning: No match for E-Mail Address and/or Password." message is displayed(file:///C:/Users/ACER/eclipse-workspace/java/TestingProject/src/test/java/cucumber/ErrorValidations.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="cucumber.TestNGTestRunner" name="runScenario" time="6.852"/>
</testsuite> <!-- cucumber.TestNGTestRunner -->
